analogdevicesinc/aditof_sdk

examples/aditof-demo/aditofdemorecorder.cpp

AditofDemo: fix partially initialized frame details

---

README.md
doc/dragonboard_firmware_build.md
doc/dragonboard_host_build.md
doc/dragonboard_target_build.md
doc/linux_build.md
doc/scripts/db410c_get_host_sw.sh
doc/scripts/db410c_get_target_sw.sh
doc/scripts/host_setup/db410c_create_kernel_image.sh
doc/scripts/host_setup/db410c_get_kernel_rootfs_dependencies.sh
doc/windows_build.md

doc: Update scripts to point to the right repos

---

examples/aditof-demo/aditofdemocontroller.cpp
examples/aditof-demo/main.cpp
sdk/src/calibration.cpp
sdk/src/system.cpp
sdk/src/system.h

This fixes the hang that happens when closing the demo application.

Windows fixes

---

sdk/src/windows/usb_device_windows.cpp

sdk: Fix hang at startup. Graph should be ran after dev programming

---

sdk/src/dragonboard/device_enumerator_dragonboard.cpp

sdk: dragonboard device enumerator: fix resource leak

---

examples/aditof-demo/CMakeLists.txt
sdk/CMakeLists.txt

sdk/examples: set CXX_STANDARD 11 property

---

doc/CMakeLists.txt

Make sure that sources dir is set correctly

---

.travis.yml
ci/travis/deps.sh
ci/travis/lib.sh
ci/travis/run_build.sh

Initial travis ci

---

README.md

Readme: add status for continuous integration

---

sdk/src/camera.cpp
sdk/src/camera.h
sdk/src/system_impl.cpp

sdk: Hide camera implementation. It should not be visible by API users

---

doc/windows/user_guide.md

doc: Add sdk build instructions on Windows

---

doc/linux/user_guide.md
doc/windows/user_guide.md

doc: Update win & linux user guides to add more informations

---

.travis.yml

Update homebrew on older macos builds

---

ci/travis/lib.sh

ci: Change doxygen folder creation: build/html -> build/doxygen_doc/html

---

sdk/src/frame_impl.cpp
sdk/src/frame_impl.h

sdk: Ensure deep copy when copying frames.

---

sdk/CMakeLists.txt

sdk: Simplify cmake by using the OS name to construct paths

---

sdk/src/dragonboard/local_device.cpp

sdk: dragonboard: optimize depth_ir deinterleave with neon arm

---

.travis.yml

On some builds the python bindings where not considered. This fixes the issue.

ci: travis: fix building of python bindigs

---

examples/aditof-demo/readme.md

examples: aditof-demo: add doc on exported frames

---

bindings/python/readme.md

bindings: python: add doc

---

bindings/python/aditofpython.cpp

Added bug-fix into the python binding regarding on how the frame is converted into an image matrix.

fix bugs in python bindings

---

bindings/python/aditofpython.cpp
bindings/python/device_example.py

Device interface python bind

---

sdk/src/network.cpp

sdk: network: Prevent from sending empty messages to server

---

README.md

merged the 2 example tables

---

scripts/linux/setup.sh

Addresses #82 / script for linux

scripts: linux: add setup script for linux

---

apps/server/server.cpp
sdk/src/device_utils.h
sdk/src/ethernet_device.cpp
sdk/src/linux/usb_device_linux.cpp
sdk/src/local_device.h
sdk/src/target/local_device.cpp
sdk/src/windows/usb_device_windows.cpp

Eth send deinterleaved data

---

scripts/dragonboard410c/setup.sh
scripts/linux/setup.sh
scripts/raspberrypi3/setup.sh

Issue #82: Script for dragonboard and raspberrypi

Dragonboard setup script

---

sdk/include/aditof/filters_factory.h
sdk/include/aditof/frame_processor.h
sdk/include/aditof/frame_processor_factory.h
sdk/include/aditof/variance_filter.h
sdk/src/filters_factory.cpp
sdk/src/variance_filter.cpp

sdk: Introduce Frame Processor

---

doc/CMakeLists.txt
sdk/include/aditof/camera.h
sdk/include/aditof/device_construction_data.h
sdk/include/aditof/device_enumerator_factory.h
sdk/include/aditof/device_enumerator_interface.h
sdk/include/aditof/device_factory.h
sdk/include/aditof/device_interface.h

sdk: Add documentation for DeviceInterface and related types

---

bindings/python/aditofpython.cpp
sdk/include/aditof/device_interface.h
sdk/src/camera_96tof1.cpp
sdk/src/ethernet_device.cpp
sdk/src/ethernet_device.h
sdk/src/linux/usb_device_linux.cpp
sdk/src/local_device.cpp
sdk/src/local_device.h
sdk/src/target/local_device.cpp
sdk/src/target/usb_device.cpp
sdk/src/usb_device.h
sdk/src/utils.cpp
sdk/src/utils.h
sdk/src/windows/usb_device_windows.cpp

sdk: clamp the values of each pixel after calibration to the range

---

examples/CMakeLists.txt
examples/first-frame-ethernet/CMakeLists.txt
examples/first-frame-ethernet/main.cpp
examples/first-frame-ethernet/readme.md
examples/readme.md

examples: add first frame examples using ip

---

cmake/readme.md

cmake: update readme

---

apps/readme.md
apps/server/README.md

apps/server: Add README

---

examples/aditof-demo/aditofdemoview.cpp
examples/aditof-demo/aditofdemoview.h

Aditofdemo improvements

---

README.md

README: update link for latest dragonboard image

---

cmake/readme.md

cmake: add for WITH_REVB cmake option

---

apps/server/server.cpp
apps/uvc-app/uvc-gadget.cpp
bindings/opencv/dnn/main.cpp
bindings/opencv/imshow/main.cpp
bindings/python/aditofpython.cpp
examples/aditof-demo/aditofdemocontroller.cpp
examples/aditof-demo/aditofdemocontroller.h
examples/first-frame-ethernet/main.cpp
examples/first-frame/main.cpp
sdk/include/aditof/camera.h
sdk/include/aditof/device_factory.h
sdk/include/aditof/filters_factory.h
sdk/include/aditof/frame.h
sdk/include/aditof/frame_processor_factory.h
sdk/include/aditof/system.h
sdk/src/calibration.cpp
sdk/src/calibration.h
sdk/src/camera_96tof1.cpp
sdk/src/camera_96tof1.h
sdk/src/camera_factory.cpp
sdk/src/camera_factory.h
sdk/src/device_factory.cpp
sdk/src/filters_factory.cpp
sdk/src/frame.cpp
sdk/src/system.cpp
sdk/src/system_impl.cpp
sdk/src/system_impl.h

This pull request adds back smart pointers in the SDK.

Add smart ptrs

---

examples/aditof-demo/CMakeLists.txt
examples/aditof-demo/aditofdemocontroller.cpp
examples/aditof-demo/aditofdemocontroller.h
examples/aditof-demo/aditofdemoview.cpp

examples/aditof_demo: 
Added options for connection mode:
- Depending on the platform used, the user can switch between the available connection modes.
Fixed small bug in the UI for "Small-signal removal"

Demo connection options

---

sdk/src/camera_96tof1.cpp

Implemented enhancement mentioned in issue: #172

sdk: camera: update range values to match those of revision C

---

apps/uvc-app/uvc-gadget.cpp
sdk/src/target/local_device.cpp

Fixes bug described in issue: #171

Fix wrong displayed color

---

.travis.yml
ci/travis/lib.sh

Remove hardcoded username, repo name, and include secure github token generated from ADI github account

ci: travis: add secure github token

---

ci/travis/lib.sh

ci/travis: Fix broken link to doxygen

---

bindings/open3D/showPointCloud/main.cpp
bindings/opencv/dnn/main.cpp
bindings/opencv/imshow/main.cpp
bindings/python/examples/dnn/dnn.py
bindings/python/examples/showPointCloud/showPointCloud.py

Methods replaced with the new methods from extended API in: open3D (point-cloud example), python (dnn and point-cloud examples) and OpenCV (dnn and imshow examples).

Replaced register writing for noise reduction

---

README.md
doc/sdcard_burn.md

doc: Update instructions for writing an SD card

---

sdk/src/linux/device_enumerator_linux.cpp

sdk: Fix usb not working on newer kernels (>=5.0) on linux hosts

---

bindings/python/aditofpython.cpp
sdk/include/aditof/camera_definitions.h
sdk/src/calibration.cpp
sdk/src/calibration.h
sdk/src/camera_96tof1.cpp

Added method to obtain the camera intrinsic parameters.

sdk: Add data structure for camera intrinsic parameters

---

bindings/opencv/dnn/main.cpp
bindings/python/examples/dnn/dnn.py

Both python and cpp examples are corrected.

DNN example: corrected the label to not exit the picture limits.

---

bindings/ros/aditof_roscpp/CMakeLists.txt
bindings/ros/aditof_roscpp/README.md
bindings/ros/aditof_roscpp/include/aditof_roscpp/aditof_sensor_msg.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/aditof_utils.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/message_factory.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/pointcloud2_msg.h
bindings/ros/aditof_roscpp/launch/rviz_publisher.launch
bindings/ros/aditof_roscpp/package.xml
bindings/ros/aditof_roscpp/rviz/pointcloud.rviz
bindings/ros/aditof_roscpp/src/aditof_utils.cpp
bindings/ros/aditof_roscpp/src/examples/rviz_pointcloud.cpp
bindings/ros/aditof_roscpp/src/message_factory.cpp
bindings/ros/aditof_roscpp/src/pointcloud2_msg.cpp

Added bindings for ros PointCloud2 message type

bindings: ros: add initial version of ROS package

---

bindings/opencv/CMakeLists.txt
bindings/opencv/aditof_opencv.h
bindings/opencv/imshow/CMakeLists.txt
bindings/opencv/imshow/main.cpp

Corrected include files.
Solves: #214

opencv/imshow: Repare not building on dragonboard bug.

---

scripts/raspberrypi3/rpi3_sdk_deps.sh

scripts: Fix cmake prefix paths in Raspberry PI script

---

scripts/linux/setup.sh
scripts/windows/readme.md
scripts/windows/setup_project.bat

Added information on how to use the windows scripts

---

cmake/readme.md

cmake/readme: Document the option to enable open3D

---

sdk/src/windows/usb_device_windows.cpp

Data is sent over USB in chunks of 58 bytes worth of actual data. The
current implementation was forcing 60 bytes, exceeding the reserved
space.
Handles https://github.com/analogdevicesinc/aditof_sdk/issues/206

sdk: Fix stack corruption in windows device when writing AFE registers

---

bindings/open3D/aditof_open3d.h
bindings/open3D/showPointCloud/main.cpp
bindings/python/examples/showPointCloud/showPointCloud.py

Apply correct intrinsic parameters for the pointcloud
Used the 16bits depth map in order to get more accurate results
Added both changes in both python and cpp examples
Solves: #175

Open3d showPointCloud: Noise corrections

---

apps/daemon/dragonboad_definitions.h
apps/daemon/main.c
apps/daemon/tof-programming.service
utils/dragonboard/config_pipe.service
utils/dragonboard/config_pipe.sh
utils/dragonboard/readme.md

Start server by default

---

utils/raspberrypi/readme.md
utils/raspberrypi/tof-server.service

Handles #165 (the part for Raspberry PI)

utils/raspberrypi: Add service for starting tof server during boot

---

doc/raspberrypi3/chicony_user_guide.md

doc: Fix chicony doc. Use 'unmounted' word instead of 'umounted'

---

ci/travis/ros_install.sh

Updates the ros_install.sh script

---

scripts/windows/readme.md
scripts/windows/setup_project.bat

Fixed bug: if you selected your own folders script was failing.
Fixed bug: help mentioned parameters that were not used.

scripts/windows Bugs fixes.

---

bindings/ros/README.md
bindings/ros/aditof_roscpp/README.md

Initial version of README.md for ros.

bindings: ros: Add documentation

---

doc/linux/build_instructions.md
doc/windows/build_instructions.md

Added bindings information in build instructions in Windows and Linux.

Documentation enhancements

---

bindings/open3D/readme.md

Bindings/open3D Corrected documentation error.

---

examples/first-frame-ethernet/main.cpp

examples: Fixed error message typos

---

bindings/open3D/readme.md

Added documentation about building the aditof project with Open3D.

Bindings/open3D: documentation.

---

doc/windows/build_instructions.md

doc: Add the missing build directory in Windows instructions

---

doc/jetson/build_instructions.md

doc: jetson: Add build instructions

---

doc/raspberrypi3/raspberrypi_firmware_build.md

doc: rpi3: Fix path to kernel zImage

---

sdk/include/aditof/camera_96tof1_specifics.h
sdk/src/camera_96tof1_specifics.cpp

This function is used to control the contrast of the IR image

Added the IR gamma conversion function

---

sdk/src/target/local_device.cpp

Seems like buf.bytesused is 0 on the dragonboard target when in fact it should be (width * height * 3 / 2) as data for the frame is packed.

sdk: target: local_device.cpp: check if buf.bytesused different from 0

---

bindings/open3D/showPointCloud/readme.md
bindings/python/examples/showPointCloud/readme.md

Open3 d documentation

---

sdk/src/calibration_96tof1.cpp

Sdk: Added max_range check for geometric calibration

---

bindings/open3D/showPointCloud/main.cpp
bindings/python/examples/showPointCloud/showPointCloud.py

Open3d show images

---

README.md
examples/first-frame-ethernet/readme.md

Documentation improvements regarding first-frame-ethernet example.

---

examples/aditof-demo/readme.md

added the correct links to the user guides.

Update documentation for demo example

---

.travis.yml
ci/travis/deps.sh
ci/travis/lib.sh

Enhancement described in issue: #287

ci: travis: build Open3D bindings on latest gcc/clang jobs

---

sdcard-images-utils/README.md
sdcard-images-utils/dragonboard410c/README.md
sdcard-images-utils/dragonboard410c/linux-patches/README.md
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_9_27/0001-dragonboard-changes.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_9_27/0002-usb-gadget-changes.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_9_27/0003-reset-fixes.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_9_27/0004-dwc3-changes.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_9_27/0005-aditof-devicetree-changes.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_9_27/0006-dts-Disable-spi0-and-disable-pull-ups.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_9_27/0007-arch-arm64-boot-dts-qcom-Enable-pin-MPP4-as-input-to.patch
sdcard-images-utils/dragonboard410c/utils/README.md
sdcard-images-utils/dragonboard410c/utils/chroot.sh
sdcard-images-utils/dragonboard410c/utils/emmc_build_boot.sh
sdcard-images-utils/dragonboard410c/utils/emmc_flash_boot.sh
sdcard-images-utils/dragonboard410c/utils/emmc_format.sh
sdcard-images-utils/dragonboard410c/utils/install_kernel_dependencies.sh
sdcard-images-utils/dragonboard410c/utils/sd_card_build_boot.sh
sdcard-images-utils/dragonboard410c/utils/sd_card_flash_boot_rootfs.sh
sdcard-images-utils/dragonboard410c/utils/sd_card_format.sh
sdcard-images-utils/dragonboard410c/utils/update_img.sh

Dgb410c image creation

---

appveyor.yml
ci/appveyor/install_glog.bat
ci/appveyor/install_protobuf.bat
ci/appveyor/install_websockets.bat
ci/appveyor/make_zip.bat

Enhancement mentioned in issue: #304 

ci: appveyor: add Visual Studio 2019 build

---

sdcard-images-utils/dragonboard410c/linux-patches/README.md
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_14_96/0001-Added-the-4.14-initial-implementation.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_14_96/0002-enable-eeprom-driver.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_14_96/0003-fix-v4l-address.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_14_96/0004-arch-arm64-boot-dts-qcom-Use-node-references.-No-fun.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_14_96/0005-DWC3-enable-driver-and-add-fixes.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_14_96/0006-webcam-Enable-module-and-make-Tof-changes.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_14_96/0007-Try-to-enable-the-2-buttons-for-mezzanine-board.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_14_96/0008-Fix-uvc_video.c-1-not-needed.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_14_96/0009-devicetree-Disable-gps-and-watchdog.patch

sdcard-images-utils: Add patches for kernel 4.14.96

---

doc/dragonboard410c/build_instructions.md

doc: Update links, now that we will be deleting aditof_linux repo

---

bindings/python/examples/dnn/dnn.py
bindings/python/examples/maskr_cnn/maskr_cnn.py
bindings/python/examples/showPointCloud/showPointCloud.py

Errors resulted from replacing cameraSpecifics with controls in sdk.

bindings/python fixed errors.

---

sdk/readme.md

doc: fix typo in sdk readme

---

cmake/aditof-config.cmake.in

use protobuf and libwesockets dependencies only if WITH_NETWORK is true

---

tools/calibration-96tof1/find_pc.py
tools/calibration-96tof1/pc_config_far.json
tools/calibration-96tof1/pc_config_mid.json
tools/calibration-96tof1/pc_config_near.json

add script and config files

---

sdk/src/cameras/ad-96tof1-ebz/calibration_96tof1.cpp

Prevent usage of invalid intrinsic parameters

---

tools/calibration-96tof1/cal_eeprom/__init__.py
tools/calibration-96tof1/cal_eeprom/cal_map.py
tools/calibration-96tof1/calibrate_single_mode.py
tools/calibration-96tof1/eeprom_replace_cal.py

add cal_eeprom folder into python path

---

apps/uvc-app/uvc-gadget.cpp
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_14_96/0008-UVC-gadget-Add-controls-for-eeprom-write-status.patch
sdcard-images-utils/dragonboard410c/linux-patches/kernel_4_9_27/0008-UVC-gadget-Add-controls-for-eeprom-write-status.patch
sdk/src/connections/usb/linux/usb_eeprom_linux.cpp
sdk/src/connections/usb/windows/usb_eeprom_windows.cpp

apps/uvc-gadget: Fix writing to EEPROM

---

scripts/windows/readme.md

Fix hashtag to better accentuate the pre-requisites portion of the readme

scripts: windows: update readme

---

tools/calibration-96tof1/cal_eeprom/cal_map.py

add imports and fix logger.json path

---

bindings/matlab/adaptor.cpp
bindings/matlab/aditofimaq.h
bindings/matlab/prop_listener.cpp
bindings/matlab/source_adaptor.cpp
bindings/matlab/source_adaptor.h
bindings/matlab/temperature_get_fcn.cpp

bindings: matlab: refactor code to use the new API

---

apps/CMakeLists.txt
apps/daemon/tof-programming.service

apps: include daemon for dragonboard when building the project

---

sdk/src/connections/target/addi9036_sensor.cpp

sdk: target: sensor_addi9036: fix compile error

---

bindings/python/aditofpython.cpp

bindings/python: Update bindings to the new API

---

bindings/python/examples/low_level_example/low_level_example.py
bindings/python/examples/low_level_example/readme.md
bindings/python/examples/readme.md

python/examples: Update example of using low level API and rename it

---

sdk/src/cameras/ad-fxtof1-ebz/calibration_fxtof1.cpp
sdk/src/cameras/ad-fxtof1-ebz/calibration_fxtof1.h
sdk/src/cameras/ad-fxtof1-ebz/camera_fxtof1.cpp
sdk/src/cameras/ad-fxtof1-ebz/camera_fxtof1.h
sdk/src/connections/target/addi9036_sensor.cpp
sdk/src/connections/target/target_sensor_enumerator.cpp
sdk/src/connections/target/toybrick/sensor_enumerator_toybrick.cpp
sdk/src/connections/target/toybrick/target_definitions.h
sdk/src/system_impl.cpp

Update FXTOF1 files to match new api 

---

apps/server/buffer.proto
apps/server/server.cpp
sdk/src/connections/network/buffer.proto
sdk/src/connections/network/network_depth_sensor.cpp

sdk: Send and receive full frame width and height over network

---

bindings/opencv/maskrcnn/readme.md

Signed-off-by: SeptimiuVana <vana.septimiu@analog.com>

Updated opencv/Maskrcnn documentation

---

sdk/src/connections/usb/linux/usb_depth_sensor_linux.cpp

A USB pachet has 60 bytes. First two contain medata, leaving 58 bytes for the payload.
But current implementation was writing 60 bytes (meaning 15 address-value pairs) over those 58 bytes.
This fixes things. If a address-value pair doesn't fit, then send address only in the first pachet and the send the value in the next pachet.

sdk: Fix overflow of data when writing it to the USB packet

---

bindings/python/aditofpython.cpp
examples/aditof-demo/aditofdemorecorder.cpp
examples/aditof-demo/readme.md
examples/first-frame-network/main.cpp
examples/first-frame/main.cpp
sdk/include/aditof/frame_definitions.h
sdk/src/cameras/ad-96tof1-ebz/camera_96tof1.cpp
sdk/src/cameras/ad-fxtof1-ebz/camera_fxtof1.cpp
sdk/src/cameras/chicony-006/camera_chicony_006.cpp
sdk/src/connections/target/addi9036_sensor.cpp
sdk/src/connections/usb/linux/usb_depth_sensor_linux.cpp
sdk/src/connections/usb/windows/usb_depth_sensor_windows.cpp
sdk/src/frame_impl.cpp
sdk/src/frame_impl.h

Remove `raw` frame type from `getAvailableFrameTypes` and rename `RAW` to `FULL_DATA` in `FrameType`

Remove raw support

---

sdk/src/connections/target/addi9036_sensor.cpp

sdk: Fix the scope of dev variable

---

bindings/open3D/aditof_open3d.h
bindings/open3D/readme.md
bindings/open3D/showPointCloud/main.cpp

Update image size of bindings/open3D

---

sdk/src/connections/target/addi9036_sensor.cpp

Update files to match FXTOF1 and RPI

---

sdk/CMakeLists.txt

use FX1 source files on all platforms, if FX1 is used

---

sdk/CMakeLists.txt
sdk/src/system_impl.cpp

prevent build if multiple cameras are selected

---

doc/CMakeLists.txt

variante_filter.h has been removed.

doc: Remove variance_filter.h

---

sdk/src/cameras/ad-96tof1-ebz/xavier_nx/sensor_enumerator_xaviernx.cpp
sdk/src/cameras/ad-fxtof1-ebz/xavier_nx/sensor_enumerator_xaviernx.cpp
sdk/src/connections/target/addi9036_sensor.cpp

Fixes:
- fix nvidia driver path
- fix pixel formating define

Release fixes

---

sdk/src/cameras/ad-fxtof1-ebz/xavier_nx/sensor_enumerator_xaviernx.cpp
sdk/src/connections/target/addi9036_sensor.cpp

remove useless line causing segmentation fault

Fix toybrick

---

scripts/build_camera.sh
scripts/rebuild_for_camera.sh

Add new script to change build files depending on configuration

---

tools/eeprom-tool/cli_helper.cpp
tools/eeprom-tool/eeprom_tool.cpp
tools/eeprom-tool/eeprom_tool.h

Fix eeprom-tool not working when on remote.

Fix eeprom tool on remote

---

scripts/windows/setup_project.bat

Update windows script to support VS 16 2019

---

sdk/src/connections/usb/linux/usb_sensor_enumerator.cpp
sdk/src/connections/usb/windows/usb_sensor_enumerator.cpp

sdk: Log the buffer containing sensor information send through USB

---

examples/aditof-test/main.cpp

examples/aditof-test: Use #ifdef not #if

---

apps/server/server.cpp

apps/server: Add missing header for the signal handling

---

README.md

Add formating info to readme

---

bindings/matlab/source_adaptor.cpp
bindings/open3D/showPointCloud/main.cpp
bindings/opencv/dnn/main.cpp
bindings/opencv/imshow/main.cpp
bindings/opencv/maskrcnn/main.cpp
bindings/python/aditofpython.cpp
bindings/python/examples/dnn/dnn.py
bindings/python/examples/maskr_cnn/maskr_cnn.py
bindings/python/examples/showPointCloud/showPointCloud.py
bindings/ros/aditof_roscpp/src/aditof_utils.cpp
examples/aditof-demo/aditofdemocontroller.cpp
examples/aditof-demo/aditofdemocontroller.h
examples/aditof-demo/aditofdemorecorder.cpp
examples/aditof-demo/aditofdemorecorder.h
examples/aditof-demo/aditofdemoview.cpp
examples/aditof-test/main.cpp
examples/imshow-jetson/main.cpp
examples/imshow-xavier/main.cpp
sdk/include/aditof/camera_definitions.h
sdk/src/cameras/ad-96tof1-ebz/camera_96tof1.cpp
sdk/src/cameras/ad-96tof1-ebz/camera_96tof1.h
sdk/src/cameras/ad-fxtof1-ebz/camera_fxtof1.cpp
sdk/src/cameras/ad-fxtof1-ebz/camera_fxtof1.h
sdk/src/cameras/chicony-006/camera_chicony_006.cpp

1) Add depth parameters to camera details (depth gain and depth offset).
2) Add controls to disable depth and geometry correction ("depth_correction" and "camera_geometry_correction").
3) Save camera parameters in capture files.

Depth parameters and frame correction options

---

sdk/src/cameras/ad-fxtof1-ebz/xavier_nx/target_definitions.h

fix temperature sensor dev path for xavier nx

---

sdk/src/cameras/ad-fxtof1-ebz/calibration_fxtof1.cpp

Adjust gain for FXTOF1

---

tools/test-fxtof1/main.cpp

Minor fix in tools/test-fxtof1

---

apps/server/server.cpp

Fix timeout of lws service in server app

---

sdk/src/cameras/ad-96tof1-ebz/calibration_96tof1.cpp

Fixing an issue introduced in this commit: https://github.com/analogdevicesinc/aditof_sdk/commit/7a7aadcb780afc585a0becee40f9d55c434ee386#diff-900b0798abcd7bc98839e2c722f282a36bca1ae4fd110e5184b0155de5900e9b

Fix geometry calibration issue

---

sdk/src/cameras/ad-fxtof1-ebz/xavier_nx/target_definitions.h

Signed-off-by: SeptimiuVana <vana.septimiu@analog.com>

Update TEMP_SENSOR_DEV_PATH for xaviernx and fxtof1

---

ci/azure/inside_docker.sh
ci/azure/lib.sh
ci/azure/run_build.sh

properly pass cmake args inside docker

---

misc/nvidia/jetson/kernel_src/hardware/nvidia/platform/t210/porg/kernel-dts/porg-platforms/tegra210-porg-camera-adi-tof.dtsi
misc/nvidia/xavier/kernel_src/hardware/nvidia/platform/t19x/common/kernel-dts/t19x-common-modules/tegra194-camera-addi9036.dtsi
misc/nvidia/xaviernx/kernel_src/hardware/nvidia/platform/t19x/common/kernel-dts/t19x-common-modules/tegra194-camera-addi9036.dtsi

Update nvidia kernel files to include FXTOF1 temp sensor

---

misc/nvidia/jetson/kernel_src/hardware/nvidia/platform/t210/porg/kernel-dts/tegra210-porg-p3448-common.dtsi

Update jetson nano kernel files

---

README.md

Update links for jetson nano img

---

apps/server/README.md
apps/server/server.cpp

server/server.cpp: fix variable name

---

apps/server/server.cpp
sdk/src/cameras/ad-fxtof1-ebz/camera_fxtof1.cpp
sdk/src/connections/network/network_depth_sensor.cpp

sdk, apps: format code

---

examples/aditof-demo/aditofdemorecorder.cpp

aditofdemorecorder.cpp: fix frame size to read/write full data

---

sdk/src/cameras/ad-96tof1-ebz/raspberrypi/target_definitions.h
sdk/src/cameras/ad-fxtof1-ebz/raspberrypi/target_definitions.h
utils/raspberrypi/53-aditofsdkraspberrypi.rules

sdk/cameras/raspberrypi: update driver paths to match new kernel

---

examples/aditof-demo/aditofdemoview.cpp

examples/aditof-demo/aditofdemoview.cpp: enable the input of all letters

---

examples/aditof-demo/aditofdemorecorder.cpp
sdk/include/aditof/frame_definitions.h
sdk/src/connections/target/addi9036_sensor.cpp
sdk/src/frame_impl.cpp
sdk/src/frame_impl.h

sdk/frame: extend frame class to include data for rbg

---

examples/aditof-demo/aditofdemoview.cpp

examples/aditof-demo/aditofdemoview.cpp: fix wrong address for ir data

---

sdk/src/cameras/ad-fxtof1-ebz/calibration_fxtof1.cpp

Fixed order mismatch when getting the intrinsic

---

sdk/src/cameras/3d-smart-camera/camera_3d_smart.cpp
sdk/src/cameras/3d-smart-camera/camera_3d_smart.h
sdk/src/frame_impl.cpp

sdk/cameras/3d-smart: Define the frame types for the camera

---

apps/server/buffer.proto
apps/server/server.cpp
apps/server/server.h
sdk/include/aditof/depth_sensor_interface.h
sdk/include/aditof/sensor_definitions.h
sdk/src/connections/network/buffer.proto
sdk/src/connections/network/network.cpp
sdk/src/connections/network/network_depth_sensor.cpp
sdk/src/connections/network/network_depth_sensor.h
sdk/src/connections/network/network_sensor_enumerator.cpp
sdk/src/connections/network/network_sensor_enumerator.h
sdk/src/connections/target/addi9036_sensor.cpp
sdk/src/connections/target/addi9036_sensor.h
sdk/src/connections/target/rgb_sensor.cpp
sdk/src/connections/target/rgb_sensor.h
sdk/src/connections/usb/linux/usb_depth_sensor_linux.cpp
sdk/src/connections/usb/macos/usb_depth_sensor_macos.cpp
sdk/src/connections/usb/usb_depth_sensor.h
sdk/src/connections/usb/windows/usb_depth_sensor_windows.cpp

apps/server/server.cpp: extend server to use rgb sensor

---

bindings/ros/ros_setup.bash
examples/aditof-demo/aditofdemoview.cpp
sdk/src/connections/target/addi9036_sensor.cpp

sdk, examples: fix for rpi aditof-demo

---

doc/CMakeLists.txt

doc: Add public header to be generated by doxygen

---

appveyor.yml
ci/appveyor/install_glog.bat
ci/appveyor/install_protobuf.bat
ci/appveyor/install_websockets.bat
ci/appveyor/make_zip.bat
doc/windows/build_instructions.md
scripts/windows/setup_project.bat

windows: keep support only for msvc 2019

---

sdk/src/system_impl.cpp

sdk: Fix badly written switch when construction cameras

---

bindings/ros/aditof_roscpp/src/cameraInfo_msg.cpp
bindings/ros/aditof_roscpp/src/depthImage_msg.cpp
bindings/ros/aditof_roscpp/src/irImage_msg.cpp
bindings/ros/aditof_roscpp/src/pointcloud2_msg.cpp
sdk/src/cameras/3d-smart-camera/camera_3d_smart.cpp
sdk/src/cameras/ad-fxtof1-ebz/camera_fxtof1.cpp

bindings/ros: revision control added and frame size correction

---

examples/aditof-demo/aditofdemocontroller.cpp
examples/aditof-demo/aditofdemocontroller.h
examples/aditof-demo/aditofdemoview.cpp
examples/aditof-demo/aditofdemoview.h

examples/aditof-demo: show far mode button only for 96tof1

---

bindings/python/aditofpython.cpp
bindings/python/examples/first_frame/first_frame.py

bindings/python: include for rgb camera

---

bindings/matlab/adaptor.cpp
bindings/matlab/aditof_imaq.m
bindings/matlab/aditofimaq.h
bindings/matlab/source_adaptor.cpp

bindings/matlab: add support for rgb camera

---

sdk/src/cameras/3d-smart-camera/camera_3d_smart.cpp

sdk/src/cameras/3d-smart-camera/: ir distortion correction added

---

bindings/python/examples/low_level_example/low_level_example.py
tools/calibration-96tof1/tof_calib/device.py

Changed call "getImageSensor" to "getImageSensors"

---

sdk/src/cameras/3d-smart-camera/calibration_3d_smart.h
sdk/src/cameras/3d-smart-camera/camera_3d_smart.cpp
sdk/src/cameras/ad-fxtof1-ebz/calibration_fxtof1.h
sdk/src/cameras/ad-fxtof1-ebz/camera_fxtof1.cpp

sdk/cameras: read serial from eeprom and populate cameraId

---

examples/aditof-demo/aditofdemoview.cpp
sdk/src/cameras/3d-smart-camera/calibration_3d_smart.cpp
sdk/src/cameras/3d-smart-camera/camera_3d_smart.cpp

solved a few warnings: [-Wsign-compare] and [-Wreorder]

---

apps/server/server.cpp
appveyor.yml
ci/appveyor/install_websockets.bat
ci/azure/lib.sh
doc/dragonboard410c/build_instructions.md
doc/jetson/build_instructions.md
doc/linux/build_instructions.md
doc/raspberrypi3/build_instructions.md
doc/windows/build_instructions.md
doc/xavier-agx/build_instructions.md
doc/xavier-nx/build_instructions.md
scripts/3dsmartcam1/sdk_update.sh
scripts/dragonboard410c/db410c_sdk_deps.sh
scripts/raspberrypi3/rpi3_sdk_deps.sh
scripts/windows/setup_project.bat

Update libwebsocket from 3.1.0 to 3.2.3

---

examples/CMakeLists.txt

examples: Add option (OFF by default) to build ImGui based demo

---

bindings/python/aditofpython.cpp
bindings/python/examples/showPointCloud/showPointCloud.py

bindings/python: fix frame size in adaptor and pointCloud size

---

examples/deps/imgui/src/examples/imgui_impl_opengl3.h

fix imgui build problem

---

bindings/ros/aditof_roscpp/src/camera_node.cpp
sdk/src/cameras/ad-96tof1-ebz/camera_96tof1.cpp
sdk/src/connections/usb/linux/usb_depth_sensor_linux.cpp

Dragonboard usb mode toggle bug fixed

---

doc/dragonboard410c/build_instructions.md
doc/jetson/build_instructions.md
doc/linux/build_instructions.md
doc/raspberrypi3/build_instructions.md
doc/windows/build_instructions.md
doc/xavier-agx/build_instructions.md
doc/xavier-nx/build_instructions.md

doc: update documentation for build process

---

azure-pipelines.yml

azure-pipelines.yml: add build for 3d smart camera

---

examples/CMakeLists.txt

examples: Include ImGui library only if WITH_IMGUI is enabled

---

scripts/3dsmartcam1/sdk_update.sh

scripts/3dsmartcam1/sdk_update.sh: add fetch command before rebuilding

---

bindings/ros/aditof_roscpp/include/aditof_roscpp/aditof_utils.h
bindings/ros/aditof_roscpp/src/aditof_utils.cpp
bindings/ros/aditof_roscpp/src/camera_node.cpp

Ros: dynamic reconfigure bug solution on host side

---

tools/eeprom-tool/cli_helper.cpp

eeprom_tool: helper correction

---

bindings/python/readme.md

bindings/python: complete readme with build steps

---

misc/nvidia/jetson/kernel_src/hardware/nvidia/platform/t210/porg/kernel-dts/tegra210-porg-p3448-common.dtsi

misc/nvidia/jetson: update dtsi included files to work with newer kernel

---

sdk/src/cameras/ad-96tof1-ebz/camera_96tof1.cpp
sdk/src/cameras/ad-fxtof1-ebz/camera_fxtof1.cpp
sdk/src/connections/target/addi9036_sensor.cpp

channels
IR and DEPTH bug, was not working induvidually, fixed with this commit
Signed-off-by: rbudai <robert.budai@analog.com>

XAVIER_NX: setting registers for enabling stream separated for specific

---

ci/azure/lib.sh
scripts/raspberrypi3/setup.sh

scripts/raspberrypi3/setup.sh: update paths to azure scripts

---

sdk/src/connections/network/network.cpp
sdk/src/connections/network/network.h

Changed m_mutex from simple mutex to recursive_mutex

---

cmake/readme.md

Updated the list of build options

---

azure-pipelines.yml
doc/windows/build_instructions.md
scripts/windows/setup_project.bat

Add support for VS 17 2022

---

cmake/version.h.cmakein

Added licence to version.h

---

doc/CMakeLists.txt
doc/linux/build_instructions.md
doc/windows/build_instructions.md

Generate doxygen doc

---

README.md

Corrected 3dsmartcam wiki link

---

bindings/python/examples/dnn/readme.md

Present the location of the necessary files

---

doc/linux/build_instructions.md
doc/windows/build_instructions.md

Update doxygen tutorial

---

doc/macos/build_instructions.md
sdk/src/connections/usb/macos/usb_depth_sensor_macos.cpp
sdk/src/connections/usb/macos/usb_sensor_enumerator.cpp
sdk/src/connections/usb/macos/usb_storage_macos.cpp

fixed methods so the sdk can be built on macOS
added build instructions for macOS

Macos Build

---

bindings/python/examples/dnn/CMakeLists.txt
bindings/python/examples/dnn/dnn.py

fixed issue #776 
added option to run example on network

Fix Python DNN example

---

doc/windows/build_instructions.md

Corrected windows build instructions

---

bindings/python/aditofpython.cpp

python/aditofpython.cpp: add pointer for RGB data as well

---

sdk/src/connections/target/addi9036_sensor.cpp

FPS drop solution for Dragonboard with ADDI9036 for tags/v3.1.0

---

sdk/CMakeLists.txt

sdk/CMakeLists.txt: handle 64bit pi flags

---

bindings/python/examples/first_frame/first_frame.py
bindings/python/examples/first_frame_network/first_frame_network.py

bindings/python/examples: update frame sizes in first-frame and first-frame-network

---

misc/nvidia/xavier/kernel_src/hardware/nvidia/platform/t19x/common/kernel-dts/t19x-common-modules/tegra194-camera-addi9036.dtsi
misc/nvidia/xavier/kernel_src/hardware/nvidia/platform/t19x/galen/kernel-dts/tegra194-p2888-0001-p2822-0000.dts

Xavier AGX device tree updated according to 5.3 kernel version

---

ci/azure/lib.sh
ci/azure/windows-build/install_deps.ps1
doc/linux/build_instructions.md
doc/macos/build_instructions.md
doc/windows/build_instructions.md
scripts/dragonboard410c/db410c_sdk_deps.sh
scripts/raspberrypi3/rpi3_sdk_deps.sh
scripts/windows/setup_project.bat

Signed-off-by: rbudai <robert.budai@analog.com>

Updated glog scripts
