analogdevicesinc/aditof_sdk

examples/aditof-demo/aditofdemoview.cpp
examples/aditof-demo/aditofdemoview.h

Make sure to call the imshow() function on the main thread as different
drawing backends may or may not support multithreading
Signed-off-by: Daniel Guramulta <Daniel.Guramulta@analog.com>

Fix demo on Windows

---

sdk/CMakeLists.txt

sdk: remove empty local_device.cpp when building on dragonboard

---

sdk/src/utils.cpp

The cache would be built for pixel values in [0, 4095) instead of [0, 4095]. This commit fixes the issue.

sdk: utils: fix bug when building calibration cache

---

examples/aditof-demo/aditofdemoview.cpp

examples: demo: cv::drawMarker() is not available in OpenCV 2

---

bindings/opencv/aditof_opencv.h

bindings: opencv: aditof_opencv.h: add missing include guards

---

sdk/src/windows/usb_device_windows.cpp

Camera could not be constructed because no device information was
provided.

sdk: Expose details about windows USB device

---

bindings/opencv/CMakeLists.txt
examples/CMakeLists.txt

This custom target can be used to copy important dlls on Windows(#109 ).
Signed-off-by: Daniel Guramulta <Daniel.Guramulta@analog.com>

CMake: add target to copy dlls to examples

---

apps/server/server.cpp
sdk/src/device_enumerator_ethernet.cpp
sdk/src/device_enumerator_ethernet.h
sdk/src/device_enumerator_factory.cpp
sdk/src/device_enumerator_impl.cpp
sdk/src/device_enumerator_impl.h
sdk/src/linux/device_enumerator_linux.cpp
sdk/src/macos/device_enumerator_macos.cpp
sdk/src/target/dragonboard/device_enumerator_dragonboard.cpp
sdk/src/target/raspberrypi/device_enumerator_raspberry.cpp
sdk/src/windows/device_enumerator_windows.cpp

There is no reason to expose them in the API.

sdk: Move implementations of DeviceEnumeratorInterface to private

---

bindings/python/CMakeLists.txt
cmake/setup.py.cmakein

Since the bindings are built at the build step along with the rest of the project, we want to use these binaries instead of asking setup.py to build them again.

bindings: Rework setup.py to skip recompiling the python bindings

---

apps/CMakeLists.txt

The server was not included even though it is supported on this platform

apps: include the server on raspberry pi target platforms

---

sdk/include/aditof/camera.h
sdk/src/camera_96tof1.cpp

In calibration mode, client code provides the firmware.
Also the data is left untouched, no corrections or clamping is done on the frames.

sdk: Add a calibration mode

---

bindings/python/aditofpython.cpp

The getCameraListAtIp was not implemented in python

bindings: python: add getCameraListAtIp method for python

---

bindings/matlab/source_adaptor.cpp
bindings/matlab/source_adaptor.h
bindings/open3D/aditof_open3d.h
bindings/open3D/showPointCloud/main.cpp
bindings/opencv/dnn/main.cpp
bindings/python/aditofpython.cpp
bindings/python/examples/dnn/dnn.py
bindings/python/examples/showPointCloud/showPointCloud.py
examples/aditof-demo/aditofdemocontroller.cpp
examples/aditof-demo/aditofdemocontroller.h
examples/aditof-demo/aditofdemoview.cpp
sdk/include/aditof/camera_definitions.h
sdk/src/camera_96tof1.cpp

Instead of the range, we will use the max possible value of a pixel.
Because there are only 12 bits that are usable from 16, the maximal value = 4095.
Fixes: #176.

Changed the calculation of the IR frame in all examples.

---

bindings/python/aditofpython.cpp

Use the approach defined in pybind11 documentation when dealing with shared pointers.
The issue was that the returned object was being destroyed on the python side leaving the camera with an invalid internal object.

bindings/python: Fix ownership policy for the objects returned by camera

---

bindings/open3D/showPointCloud/main.cpp
bindings/opencv/dnn/main.cpp
bindings/opencv/imshow/main.cpp
bindings/python/aditofpython.cpp
bindings/python/examples/dnn/dnn.py
bindings/python/examples/showPointCloud/showPointCloud.py
examples/aditof-demo/aditofdemocontroller.cpp
examples/aditof-demo/aditofdemocontroller.h
examples/aditof-demo/aditofdemoview.cpp
examples/aditof-demo/aditofdemoview.h
sdk/include/aditof/camera_definitions.h
sdk/src/camera_96tof1.cpp
sdk/src/camera_96tof1.h

Added minimum extremity range in camera details.
Used the minimum extremity range to correct the values in colored depth map.
Solves #185 

Demo: Colored depth map values correction by using minimum range

---

bindings/open3D/aditof_open3d.h
bindings/open3D/showPointCloud/main.cpp

Added the usage of Minimum depth range in the construction of the depth image.

Open3d: fixed depth construction with ranges.

---

bindings/python/aditofpython.cpp
bindings/python/examples/showPointCloud/showPointCloud.py
examples/aditof-demo/aditofdemocontroller.cpp
examples/aditof-demo/aditofdemocontroller.h
examples/aditof-demo/aditofdemoview.cpp
sdk/include/aditof/camera_96tof1_specifics.h
sdk/src/camera_96tof1.cpp
sdk/src/camera_96tof1.h
sdk/src/camera_96tof1_specifics.cpp

Revision can be selected and the value for the MaxDepth changes accordingly.
Added example of usage in the demo application.
Solves #186.

sdk: Add option to select the revision in camera specifics

---

sdk/src/target/dragonboard/device_enumerator_dragonboard.cpp

Bug is in the dragonboard implementation.

sdk: Fix buffer overrun and memory leak in device enumerator

---

sdk/src/system_impl.h

sdk: Add missing include. Fixes compile error on MSVC.

---

sdk/src/calibration.cpp

sdk: Use float representation when saving sizes to EEPROM

---

examples/aditof-demo/aditofdemoview.cpp

Right after startup of the demo application if one enables the small signal removal, the feature will be enabled with a default threshold of 0 instead of default value set in UI which is 50.

examples/aditof_demo: Apply threshold when enabling small signal removal

---

examples/aditof-demo/aditofdemoview.cpp
examples/aditof-demo/aditofdemoview.h

Disabled the state of noise reduction when switching between modes.
Simplified the code, to use only 2 variables, not 3.
Solves #183 

Demo: noise reduction issue

---

examples/aditof-demo/aditofdemoview.cpp

The value of the small signal threshold it is changed if the backspace is pressed.
Solves: #232

Demo: solved noise reduction bug.

---

apps/daemon/main.c

It's about the S4 button on ad-96tof1-ebz.
These depend on the changes made in the device tree where the pin in enabled as input.

apps/daemon: Update the id of the second button (S4)

---

bindings/matlab/source_adaptor.cpp
bindings/matlab/source_adaptor.h

Build was failing due to a change in the structure of the camera details. Now the depth image should be converted to pixels according to the minimum and maximum depth value it can measure in the desired mode. 
Fixes issue: #237  

bindings: matlab: fix adaptor build

---

examples/aditof-demo/aditofdemoview.cpp
sdk/include/aditof/status_definitions.h
sdk/src/camera_96tof1_specifics.cpp

Because of hardware limitations, noise reduction does not work in far mode.
This is disabled from extended camera API.

Demo: far mode does not support noise reduction.

---

doc/dragonboard410c/user_guide.md

Poweroff will turn off the board for a couple of seconds and reboot the board afterwards.
Halt doesn't reboot.

doc: Use 'halt' over 'poweroff' in dragonboard doc

---

.travis.yml
CMakeLists.txt
bindings/ros/CMakeLists.txt
bindings/ros/aditof_roscpp/CMakeLists.txt
bindings/ros/ros_setup.bash
ci/travis/deps.sh
ci/travis/ros_install.sh
ci/travis/run_build.sh

Added two more jobs in travis.yml file, for the latest ROS distributions.
Building the ROS package is enabled by setting a cmake parameter, similarly to the other bindings.

Provide CI for ROS package

---

bindings/ros/aditof_roscpp/src/aditof_utils.cpp

The default connection type is now USB.

bindings: ros: Add support for camera connected over USB

---

.clang-format

If comments break the 80 chars per line rule, don't reflow them. This is
the case of the license headers in all files as they currently take more
than 80 chars on some lines.

.clang-format: don't reflow comments

---

bindings/opencv/CMakeLists.txt

The define for opencv version 2 was set for all versions less than 3.4.1. The correct define should be set only for versions less than 3.0.0

bindings: opencv: properly identify opencv version 2

---

CMakeLists.txt
cmake/udev-rules-install.cmake
scripts/dragonboard410c/setup.sh
scripts/jetson/setup.sh
scripts/raspberrypi3/setup.sh
utils/dragonboard/53-aditofsdkdragonboard.rules
utils/dragonboard/readme.md
utils/jetson/53-aditofsdkjetson.rules
utils/jetson/readme.md
utils/raspberrypi/53-aditofsdkraspberrypi.rules
utils/raspberrypi/readme.md

Added udev-rules for eeprom access, for Dragonboard, Raspberrypi, Jetson.
Solves #235

Added udev-rules

---

bindings/open3D/readme.md

When building Open3D (v0.9.0.0) from source, the ABI for C++11 is disabled by default. And this perpetuates (as compiler flags) to the showPointCloud example and the SDK that make use of C++11 features, making them to not work properly or even not compile.

bindings/open3d: Update README with options to build Open3D

---

bindings/ros/aditof_roscpp/src/pointcloud2_msg.cpp

In order to obtain the z coordinate, we need to perform computations on the depth value

bindings: ros: Fix the depth data processing to obtain the z coordinate

---

doc/raspberrypi3/build_instructions.md

Add link to devicetree used for RPi platform on build instructions page.

doc: rpi: Add devicetree link for Rpi

---

bindings/ros/aditof_roscpp/include/aditof_roscpp/aditof_sensor_msg.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/aditof_utils.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/message_factory.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/pointcloud2_msg.h
bindings/ros/aditof_roscpp/src/aditof_utils.cpp
bindings/ros/aditof_roscpp/src/examples/rviz_pointcloud.cpp
bindings/ros/aditof_roscpp/src/message_factory.cpp
bindings/ros/aditof_roscpp/src/pointcloud2_msg.cpp

An AditofSensorMsg object is now created based on a Frame object.
In the previous version, creating a new message implied requesting
a new frame, which is incorrect.
This change is needed because the camera node will create different
types of messages based on the same frame.

bindings: ros: Code refactor for frame-based message

---

bindings/ros/aditof_roscpp/include/aditof_roscpp/aditof_utils.h
bindings/ros/aditof_roscpp/rviz/pointcloud.rviz
bindings/ros/aditof_roscpp/src/aditof_utils.cpp
bindings/ros/aditof_roscpp/src/pointcloud2_msg.cpp

Use intensity channel instead of rgb channel and set
the values accordingly (IR data instead of depth data).

bindings: ros: Use IR data to color point cloud

---

bindings/ros/aditof_roscpp/include/aditof_roscpp/cameraInfo_msg.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/depthImage_msg.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/irImage_msg.h
bindings/ros/aditof_roscpp/src/cameraInfo_msg.cpp
bindings/ros/aditof_roscpp/src/depthImage_msg.cpp
bindings/ros/aditof_roscpp/src/irImage_msg.cpp
bindings/ros/aditof_roscpp/src/message_factory.cpp

Added  new classes that encapsulate the CameraInfo and
Image messages defined in the ros package sensor_msgs.
There are two types for the Image message, an 8-bit
RGB depth image and a 16-bit grayscale IR one.

bindings: ros: Add image and camera_info messages

---

utils/dragonboard/config_pipe.service

This is a trivial service that needs to start successfully in order to have
the aditof-demo running, otherwise a manual run of the config-pipe.sh
script is needed. On some "boots" this service fails to start due to being
unable to open "/dev/media1". In this case the service could try to restart
after a while, and keep restarting until it is successful

utils: dragonboard: restart config pipe service if it fails

---

bindings/ros/aditof_roscpp/CMakeLists.txt
bindings/ros/aditof_roscpp/include/aditof_roscpp/message_factory.h
bindings/ros/aditof_roscpp/src/camera_node.cpp
bindings/ros/aditof_roscpp/src/message_factory.cpp

bindings: ros: message factory missing type - Add missing message type needed by the camera node
bindings: ros: Add camera node - The camera node is used to publish all message types supported     by the aditof_roscpp package.

bindings: ros: Ros camera_node

---

sdk/src/target/jetson/target_definitions.h

Build of Jetson SDK is failaing due to not finding "TEMP_REPLACEMENT_PATH" 
variable. This commit fix that.

sdk: jetson: Add TEMP_REPLACEMENT_PATH

---

bindings/ros/aditof_roscpp/include/aditof_roscpp/aditof_utils.h
bindings/ros/aditof_roscpp/launch/camera_node.launch
bindings/ros/aditof_roscpp/launch/rviz_publisher.launch
bindings/ros/aditof_roscpp/src/aditof_utils.cpp

This commit adds the parseArgs function, used to obtain the IP
parameter, if it exists. Otherwise, the USB connection type is employed.
Also changed both launch files in order to set a default value for the IP
param and removed threshold as command line argument from launch file.

bindings: ros: Fix connection type bug

---

bindings/ros/aditof_roscpp/src/aditof_utils.cpp

Before this commit, the data array given as parameter to
the irTo16bitGrayscale function was not updated with
the values resulted after processing.

bindings: ros: Fix ir image message

---

examples/imshow-jetson/main.cpp

On imshow-jetson example there is generated a segmentation fault
when chicony camera is used due to returned null pointer.
This commit fix that.

sdk: jetson: imshow-jetson: Fix seg fault with chicony cam

---

bindings/ros/aditof_roscpp/cfg/Aditof_roscpp.cfg
bindings/ros/aditof_roscpp/include/aditof_roscpp/aditof_utils.h
bindings/ros/aditof_roscpp/src/aditof_utils.cpp
bindings/ros/aditof_roscpp/src/camera_node.cpp

This commit adds the option to change the ir gamma correction
parameter's value from the rqt_reconfigure interface.

bindings: ros: add IR gamma correction parameter

---

examples/aditof-demo/aditofdemoview.cpp

Added length limit for gamma correction value input.
Made sure the user cannot input for gamma correction ".", as a start value, as this generates a fatal error.
Made sure only one "." can be inputed for the gamma correction value.

Demo: Ui fixes - gamma correction

---

bindings/ros/aditof_roscpp/src/cameraInfo_msg.cpp

The K matrix contained in the camera_info message was missing a row.

bindings: ros: Fix camera_info msg matrix

---

bindings/ros/aditof_roscpp/include/aditof_roscpp/aditof_sensor_msg.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/cameraInfo_msg.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/depthImage_msg.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/irImage_msg.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/message_factory.h
bindings/ros/aditof_roscpp/include/aditof_roscpp/pointcloud2_msg.h
bindings/ros/aditof_roscpp/src/cameraInfo_msg.cpp
bindings/ros/aditof_roscpp/src/camera_node.cpp
bindings/ros/aditof_roscpp/src/depthImage_msg.cpp
bindings/ros/aditof_roscpp/src/examples/rviz_pointcloud.cpp
bindings/ros/aditof_roscpp/src/irImage_msg.cpp
bindings/ros/aditof_roscpp/src/message_factory.cpp
bindings/ros/aditof_roscpp/src/pointcloud2_msg.cpp

The camera node creates 4 messages based on the same frame, but each
message contains a different timestamp.This commit assures that all
4 messages have the same timestamp.

bindings: ros: Fix messages timestamp

---

sdk/CMakeLists.txt

Fix build error when WITH_NETWORK=OFF - with the existing implementation only the files for network_device were being removed from the build list.

Fix build for WITH_NETWORK=OFF

---

examples/CMakeLists.txt

I don't see any reason to build the first-frame-ethernet example when network support is disabled.

examples: Activate first-frame-eth only when network support is ON

---

sdk/src/connections/usb/linux/usb_linux_utils.cpp

usb_linux_utils.cpp fix int ret initialization on line 134, this cause error on Yocto GCC 7.3.0

GCC 7.3.0 fix for usb_linux_utils.cpp

---

examples/aditof-demo/aditofdemocontroller.cpp

This assumes that the target enumerates the sensors in the following order: AfeTemperatureSensor, LaserTemperatureSensor

examples: aditof-demo: fix temperature readings

---

examples/aditof-demo/aditofdemorecorder.cpp
examples/aditof-demo/aditofdemoview.cpp
examples/imshow-jetson/main.cpp
sdk/include/aditof/frame_definitions.h
sdk/src/cameras/ad-96tof1-ebz/camera_96tof1.cpp
sdk/src/connections/mipi/dragonboard/target_definitions.h
sdk/src/connections/mipi/jetson/target_definitions.h
sdk/src/connections/mipi/local_device.cpp
sdk/src/connections/mipi/raspberrypi/target_definitions.h
sdk/src/connections/usb/linux/usb_device_linux.cpp
sdk/src/connections/usb/windows/usb_device_windows.cpp
sdk/src/frame_impl.cpp
sdk/src/local_device.h
sdk/src/usb_device.h

Add `fullDataWidth` and `fullDataHeight` to `FrameDetails` and refactor the whole code (except uvc-gadget) in order to use the proper size depending on the needed values.
By this change there should be no more division / multiplication by 2 for frame size. Those operations were needed because on some platforms one frame is actually a container for 2 frames (IR and Depth).

Extend frame details

---

bindings/python/aditofpython.cpp
sdk/include/aditof/connections.h
sdk/src/connections/mipi/toybrick/device_enumerator_toybrick.cpp
sdk/src/connections/target/addi9036_sensor.cpp
tools/eeprom-tool/cli_helper.cpp
tools/eeprom-tool/cli_helper.h
tools/eeprom-tool/eeprom_tool.cpp
tools/eeprom-tool/main.cpp
tools/eeprom-tool/tester.py

Avoid naming conflict between cmake define TARGET and enum element

---

sdk/src/connections/target/addi9036_sensor.cpp

sdk: target: addi9036_sensor: fix empty driver sub path on rpi

---

sdk/src/connections/target/addi9036_sensor.cpp

use aux variable in order to preserve original address when reading AFE registers

---

sdk/src/connections/network/network_depth_sensor.cpp

It was observed that only half the IR images was being displayed.

sdk: Fix sizes when deinterleaving frame obtained over network

---

sdk/src/cameras/ad-96tof1-ebz/calibration_96tof1.cpp
sdk/src/cameras/ad-96tof1-ebz/camera_96tof1.cpp
sdk/src/frame_impl.cpp

Fixes: 
- Fix buffer size allocation for frame
- Replace deprecated `device` usage with `depthSensor`
- Naming convention fix method argument

Fixes for nx

---

sdk/src/cameras/chicony-006/calibration_chicony_006.cpp
sdk/src/system_impl.cpp

Fixes:
- Move search of AfeTempSensor and LaserTempSensor in the macro else-branch that runs if neither Chicony nor FXTOF1 are selected (as those sensors do not exist in the case of these cameras)
- Fix chicony calibration constructor by copying the eeprom pointer into the local member
- Rename deprecated `device` to `sensor`
- Remove uneeded `;`

Chicony fixes

---

sdcard-images-utils/dragonboard410c/utils/chroot.sh

This will make sure that opencv examples and python calibration tools see the opencv which is installed at /usr/local.
Also, ldconfig is required for the new paths to apply.

sdcard: Fix paths for opencv pkconfig file

---

examples/aditof-test/main.cpp

filesystem is not a header in C++11 standard library.

examples/aditof-test: Fix build error because of included header

---

sdk/src/cameras/ad-96tof1-ebz/calibration_96tof1.cpp
tools/eeprom-tool/cam96tof1_eeprom.cpp

Writing value 100 near the end of the EEPROM doesn't help reading the size of the EEPROM. So we remove the write operation.

Remove un-needed write to EEPROM for AD-96TOF1-EBZ

---

sdk/src/cameras/ad-96tof1-ebz/xavier_agx/sensor_enumerator_xavier.cpp

In L4T 32.5 kernel update the video subdevs enumeration order was
changed. Update SDK accordingly.
Signed-off-by: btogorean <bogdan.togorean@analog.com>

sdk: camera: xavier agx: Update subdev name for L4T 32.5

---

sdk/src/cameras/ad-96tof1-ebz/calibration_96tof1.cpp

Specify the key values and coefficients orders:
INTRINSIC for [fx, 0, cx, 0, fy, cy, 0, 0, 1]
DISTORTION_COEFFICIENTS for [k1, k2, p1, p2, k3]

Change comment for getIntrinsic()

---

sdk/include/aditof/frame.h
sdk/include/aditof/system.h

warning C4251: 'aditof::System::m_impl': class
'std::unique_ptr<SystemImpl,std::default_delete<SystemImpl>>' needs to
have dll-interface to be used by clients of class 'aditof::System'
warning C4251: 'aditof::Frame::m_impl': class
'std::unique_ptr<FrameImpl,std::default_delete<FrameImpl>>' needs to
have dll-interface to be used by clients of class 'aditof::Frame'

sdk/include: Remove windows warning warning C4251

---

misc/nvidia/jetson/kernel_src/kernel/kernel-4.9/drivers/media/i2c/addi9036.c

Do not print in DMESG error message for I2C write failure.
Messages can still be enabled using dynamic_debug

misc: kernel_src: addi9036.c: Downgrade I2C error message

---

examples/aditof-demo/aditofdemocontroller.cpp
examples/aditof-demo/safequeue.h

What was happening was that after clicking the stop button and then
click start again, the memory usage (on Windows) was increasing by 1.4
GB. And this could go on for each stop->start iteration.
The fix is to clear the queue with captured frames when stopping the
stream capture. Otherwise the next captuing will start with a large
queue (thinking it's empty) and appending new frames to that.

examples/aditof-demo: Fix memory leak by learing queue with frames

---

misc/nvidia/jetson/kernel_src/kernel/kernel-4.9/drivers/media/i2c/addi9036.c

Write only start at 0x7CA0 according to datasheet so fix allowed range

misc: jetson: drivers: addi9036: Fix regmap read allowed range

---

bindings/ros/aditof_roscpp/cfg/Aditof_roscpp.cfg
bindings/ros/aditof_roscpp/include/aditof_roscpp/depthImage_msg.h
bindings/ros/aditof_roscpp/src/camera_node.cpp
bindings/ros/aditof_roscpp/src/depthImage_msg.cpp

ROS binding: added dropdown menu for depth data format between (MONO16 and RGBA8)

ROS: camera_node corrections

---

sdk/src/cameras/3d-smart-camera/camera_3d_smart.cpp
sdk/src/cameras/3d-smart-camera/camera_3d_smart.h
sdk/src/cameras/ad-96tof1-ebz/camera_96tof1.cpp
sdk/src/cameras/ad-96tof1-ebz/camera_96tof1.h
sdk/src/cameras/ad-fxtof1-ebz/camera_fxtof1.cpp
sdk/src/cameras/ad-fxtof1-ebz/camera_fxtof1.h

And make this option to be disabled by default. It lowers the FPS
especially on target.

sdk: Add option to enable IR distorsion correctio

---

sdk/CMakeLists.txt

In case the system on which the sdk is built does not include atomic library by default, manual linking is done by the cmake.

Kuyper build problem solved

---

CMakeLists.txt
sdk/CMakeLists.txt

JS bindings are generated using WITH_JS option. When creating the JS bindings, connections directory doesn't need to be added in the build.

Changed build configuration for JavaScript bindings

---

misc/nvidia/jetson/kernel_src/kernel/kernel-4.9/drivers/media/i2c/addi9036.c

v4l_subdeb_video_ops got parameter removed after kernel version update: .g_mbus_config

ADDI9036 driver: v4l_subdeb_video_ops bug fix
